navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img:
    icon:
    title: 无语小站
  menu:
    - name: 博客
      icon: fas fa-rss
      url: /
  cover:
      height_scheme: half
      scheme: focus
  blogger:
    class: blogger
    display: [mobile]
    avatar: http://q2.qlogo.cn/headimg_dl?dst_uin=2035650646&spec=100
    title: Blank
    subtitle: 怀最好的期盼，做最坏的打算。
    jinrishici: true
    social: true
    color_scheme: 
   # ------------
   # 通用颜色
    common:
    # 主题色
    theme: '#5E72E4'
    # 链接色
    link: '#2196f3'
    # 按钮色
    button: '#44D7B6'
    # 鼠标放到交互元素上时的色
    hover: '#ff5722'
    # 主题色块内部的文字颜色
    inner: '#fff'
    # 选中区域文字的背景颜色
    selection: 'alpha(#2196f3, 0.2)'
  # ------------
  # 亮色主题（默认）
  light:
    # 网站背景色
    site_bg: '#f4f4f4'
    # 网站背景上的文字
    site_inner: '#000000'
    # 网站页脚文字
    site_footer: '#000000'

    # 卡片背景色
    card: '#fff'
    # 卡片上的普通文字
    text: '#444'

    # 区块和代码块背景色
    block: '#f6f6f6'
    # 代码块高亮时的背景色
    codeblock: '#FFF7EA'
    # 行内代码颜色
    inlinecode: '#D56D28'

    # 文章部分
    h1: '#444'
    h2: '#444'
    h3: '#444'
    h4: '#444'
    h5: '#444'
    h6: '#444'
    p: '#444'

    # 列表文字
    list: '#666'
    # 列表 hover 时的文字
    list_hl: 'mix($color-theme, #000, 80)'
    # 辅助性文字
    meta: '#888'